apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/hammoud-abdellah/devops.git
      targetRevision: HEAD
      path: yaml-files
    - repoURL: https://github.com/hammoud-abdellah/devops-frontend.git
      targetRevision: HEAD
      path: yaml-files
  destination: 
    server: https://kubernetes.default.svc
    namespace: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true